ratings:
  namespace: student33-bookinfo-uat
  image: ghcr.io/aot25922/bookinfo-ratings-details
  tag: uat
  replicas: 1
  imagePullSecrets: registry-bookinfo
  port: 8080
  healthCheckPath: "/health"
ingress:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  host: bookinfo.uat.opsta.net
  path: "/student33/details(/|$)(.*)"
  serviceType: ClusterIP
