apiVersion: v1
description: Bookinfo Ratings Details Service Helm Chart
name: bookinfo-ratings-details
version: 1.0.0
appVersion: 1.0.0
home: https://bookinfo.dev.opsta.net/student33/details
maintainers:
  - name: student33
    email: devop033@mail.kmutt.ac.th
sources:
  - https://github.com/Aot25922/bookinfo-ratings-details